# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            isabelgk
tagline:          ''
description:      ''
url:              http://www.isabelgk.com
baseurl:          /

author:
  name:           'Isabel Kaspriskie'
  url:            https://github.com/isabelgk

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/isabelgk/isabelgk.com